fail_fast: true
repos:
  - repo: local
    hooks:
      - id: autoflake
        stages: [commit]
        name: autoflake
        entry: autoflake
        language: system
        types: [python]
        args:
          - --in-place
          - --remove-all-unused-imports
          - --expand-star-imports
          - --ignore-init-module-imports
  - repo: local
    hooks:
      - id: isort
        stages: [commit]
        name: isort
        entry: isort
        language: system
        types: [python]
        args:
          - --atomic
          - --force-alphabetical-sort-within-sections
          - --remove-redundant-aliases
          - --profile=black
  - repo: local
    hooks:
      - id: black
        stages: [commit]
        name: black
        entry: black
        language: system
        types: [python]
        files: .
  - repo: local
    hooks:
      - id: flake8
        stages: [commit]
        name: flake8
        entry: flake8
        language: system
        types: [python]
        files: (app|tests)
  # - repo: local
  #   hooks:
  #     - id: pytest
  #       stages: [push]
  #       name: pytest
  #       entry: pytest
  #       language: system
  #       files: test*.py
  #       always_run: true
