version: '3'
services:
  postgis:
    build: postgis
    environment:
    - POSTGRES_PASSWORD=batimap
    - POSTGRES_USER=docker
    - POSTGRES_DB=gis
    ports:
    - "5432:5432"
    volumes:
    - ./postgis/data:/var/lib/postgresql/data
    networks:
      fixed_network:
        ipv4_address: 10.5.0.10

  initializer:
    build: initializer
    environment:
    - POSTGRES_PASSWORD=batimap
    - POSTGRES_USER=docker
    - POSTGRES_DB=gis
    - POSTGRES_HOST=10.5.0.10
    # - REGIONS=france/rhone-alpes-latest
    entrypoint: bash /wait-for-it.sh -- /import_from_geofabrik.sh $$REGIONS
    depends_on:
    - postgis
    volumes:
    - ./initializer/data:/tmp/batimap-init
    networks:
      fixed_network:
        ipv4_address: 10.5.0.250

  tiles:
    build: tiles
    command: bash /wait-for-it.sh --host=10.5.0.10 --port=5432 --user=docker --password=batimap --db=gis -- tegola --config /root/config.toml serve
    ports:
    - "9999:9999"
    volumes:
    - ./tiles/:/root
    depends_on:
    - postgis
    networks:
      fixed_network:
        ipv4_address: 10.5.0.11

  backend:
    build: backend
    environment:
    - POSTGRES_PASSWORD=batimap
    - POSTGRES_USER=docker
    - POSTGRES_DB=gis
    - POSTGRES_HOST=10.5.0.10
    - POSTGRES_PORT=5432
    - FLASK_APP=app.py
    command: bash /wait-for-it.sh -- flask initdb && flask run -h 0.0.0.0
    ports:
    - "5000:5000"
    volumes:
    - ./backend/:/code
    depends_on:
    - postgis
    networks:
      fixed_network:
        ipv4_address: 10.5.0.12

  frontend:
    build: frontend
    ports:
    - "4200:4200"
    volumes:
    - ./frontend/:/usr/src/app
    depends_on:
    - tiles
    - backend
    networks:
      fixed_network:
        ipv4_address: 10.5.0.13

networks:
  fixed_network:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
