version: '3'
services:
  postgis:
    build: postgis
    env_file:
    - ./.env
    ports:
    - "5432:5432"
    volumes:
    - ./postgis/data:/var/lib/postgresql/data
    networks:
      fixed_network:
        ipv4_address: 10.5.0.10

  imposm_updater:
    build: imposm_updater
    env_file:
    - ./.env
    entrypoint: bash /wait-for-it.sh -- /import_from_geofabrik.sh $$REGIONS
    depends_on:
    - postgis
    volumes:
    - ./imposm_updater/data:/app
    networks:
      fixed_network:
        ipv4_address: 10.5.0.11

  tiles:
    build: tiles
    env_file:
    - ./.env
    command: bash /wait-for-it.sh -- tegola --config $$CONFIG serve
    volumes:
    - ./tiles/:/app
    ports:
    - "9999:9999"
    depends_on:
    - postgis
    networks:
      fixed_network:
        ipv4_address: 10.5.0.12

  tiles-cleaner:
    build: tiles-cleaner
    env_file:
    - ./.env
    command: bash /entrypoint.sh
    volumes:
    - ./tiles/:/app
    networks:
      fixed_network:
        ipv4_address: 10.5.0.13

  initdb_worker:
    build: initdb_worker
    volumes:
    - ./initdb_worker/:/code
    - ./imposm_updater/data/tiles:/tiles
    networks:
      fixed_network:
        ipv4_address: 10.5.0.14

  redis:
    image: redis:4-alpine
    command: redis-server
    volumes:
      - ./redis/data:/var/lib/redis/data
    ports:
      - '6379:6379'
    networks:
      fixed_network:
        ipv4_address: 10.5.0.15

  celery:
    build: backend
    env_file:
    - ./.env
    command: sh /wait-for-it.sh -- celery -A app.celery worker --loglevel=info
    volumes:
    - ./backend/:/code
    - ./tiles/data/outdated:/code/tiles
    depends_on:
    - postgis
    networks:
      fixed_network:
        ipv4_address: 10.5.0.16

  backend:
    build: backend
    env_file:
    - ./.env
    command: sh /wait-for-it.sh -- sh /entrypoint.sh
    ports:
    - "5000:5000"
    volumes:
    - ./backend/:/code
    - ./tiles/data/outdated:/code/tiles
    depends_on:
    - postgis
    networks:
      fixed_network:
        ipv4_address: 10.5.0.17

  frontend:
    build: frontend
    ports:
    - "4200:4200"
    volumes:
    - ./frontend/:/usr/src/app
    depends_on:
    - tiles
    - backend
    networks:
      fixed_network:
        ipv4_address: 10.5.0.18

networks:
  fixed_network:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
