version: '3'
services:
  postgis:
    build: postgis
    environment:
    - POSTGRES_PASSWORD=batimap
    - POSTGRES_USER=docker
    - POSTGRES_DB=gis
    ports:
    - "5432:5432"
    volumes:
    - ./postgis/data:/var/lib/postgresql/data
    networks:
      fixed_network:
        ipv4_address: 10.5.0.10

  imposm_updater:
    build: imposm_updater
    environment:
    - POSTGRES_PASSWORD=batimap
    - POSTGRES_USER=docker
    - POSTGRES_DB=gis
    - POSTGRES_HOST=10.5.0.10
    - POSTGRES_PORT=5432
    # - REGIONS=france/rhone-alpes-latest
    # - FORCE_IMPORT=true
    entrypoint: bash /wait-for-it.sh -- /import_from_geofabrik.sh $$REGIONS
    depends_on:
    - postgis
    volumes:
    - ./imposm_updater/data:/app
    networks:
      fixed_network:
        ipv4_address: 10.5.0.11

  tiles:
    build: tiles
    environment:
    - POSTGRES_PASSWORD=batimap
    - POSTGRES_USER=docker
    - POSTGRES_DB=gis
    - POSTGRES_HOST=10.5.0.10
    - POSTGRES_PORT=5432
    command: bash /wait-for-it.sh -- tegola --config $$CONFIG serve
    volumes:
    - ./tiles/:/app
    ports:
    - "9999:9999"
    depends_on:
    - postgis
    networks:
      fixed_network:
        ipv4_address: 10.5.0.12

  tiles-cleaner:
    build: tiles-cleaner
    environment:
    - INITIAL_MAX_ZOOM=7
    - POSTGRES_PASSWORD=batimap
    - POSTGRES_USER=docker
    - POSTGRES_DB=gis
    - POSTGRES_HOST=10.5.0.10
    - POSTGRES_PORT=5432
    command: bash /wait-for-it.sh -- /entrypoint.sh
    volumes:
    - ./tiles/:/app
    depends_on:
    - postgis
    networks:
      fixed_network:
        ipv4_address: 10.5.0.13

  backend:
    build: backend
    environment:
    - POSTGRES_PASSWORD=batimap
    - POSTGRES_USER=docker
    - POSTGRES_DB=gis
    - POSTGRES_HOST=10.5.0.10
    - POSTGRES_PORT=5432
    - FLASK_APP=app.py
    # - CONFLATION_VERBOSITY=DEBUG
    command: bash /wait-for-it.sh -- bash /entrypoint.sh
    ports:
    - "5000:5000"
    volumes:
    - ./backend/:/code
    - ./tiles/data/outdated:/code/tiles
    depends_on:
    - postgis
    networks:
      fixed_network:
        ipv4_address: 10.5.0.14

  frontend:
    build: frontend
    ports:
    - "4200:4200"
    volumes:
    - ./frontend/:/usr/src/app
    depends_on:
    - tiles
    - backend
    networks:
      fixed_network:
        ipv4_address: 10.5.0.15

networks:
  fixed_network:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
