version: "3"
services:
  postgis:
    image: registry.gitlab.com/bagage/batimap/postgis
    env_file:
      - ./.env
    volumes:
      - ./data/postgis:/var/lib/postgresql/data

  imposm:
    image: registry.gitlab.com/bagage/batimap/imposm
    env_file:
      - ./.env
    entrypoint: bash /wait-for-it.sh -- /entrypoint.sh $$REGIONS
    depends_on:
      - postgis
    volumes:
      - ./data/imposm:/data

  imposm-watcher:
    image: registry.gitlab.com/bagage/batimap/imposm-watcher
    volumes:
      - ./data/imposm/updated-tiles:/data

  tiles:
    image: registry.gitlab.com/bagage/batimap/tiles
    env_file:
      - ./.env
    command: bash /wait-for-it.sh -- tegola --config $$CONFIG serve
    volumes:
      - ./data/tiles/cache:/data/cache
    depends_on:
      - postgis

  tiles-cleaner:
    image: registry.gitlab.com/bagage/batimap/tiles-cleaner
    env_file:
      - ./.env
    command: bash /entrypoint.sh
    volumes:
      - ./data/tiles:/data

  redis:
    image: redis:5-alpine
    command: redis-server --appendonly yes
    volumes:
      - ./data/redis:/data

  celery:
    image: registry.gitlab.com/bagage/batimap/back
    env_file:
      - ./.env
    command: bash /wait-for-it.sh -- celery -A batimap.app_celery:app worker --loglevel=info
    volumes:
      - ./back/app-docker.conf/:/code/batimap/app.conf:ro
      - ./data/tiles:/code/tiles
    depends_on:
      - redis
      - postgis

  back:
    image: registry.gitlab.com/bagage/batimap/back
    env_file:
      - ./.env
    command: bash /wait-for-it.sh -- sh /entrypoint.sh
    volumes:
      - ./back/app-docker.conf/:/code/batimap/app.conf:ro
      - ./data/tiles:/code/tiles
    depends_on:
      - postgis

  front:
    image: registry.gitlab.com/bagage/batimap/front
    depends_on:
      - tiles
      - back
