version: '3'
services:
  postgis:
    build: postgis
    env_file:
    - ./.env
    ports:
    - "5432:5432"
    volumes:
    - ./data/postgis:/var/lib/postgresql/data
    networks:
      fixed_network:
        ipv4_address: 10.8.0.10

  imposm:
    build: imposm
    env_file:
    - ./.env
    entrypoint: bash /wait-for-it.sh -- /entrypoint.sh $$REGIONS
    depends_on:
    - postgis
    volumes:
    - ./data/imposm:/app
    networks:
      fixed_network:
        ipv4_address: 10.8.0.11

  citystats-refresher:
    build: citystats-refresher
    volumes:
    - ./citystats-refresher/:/code
    - ./data/imposm/tiles:/tiles
    restart: always
    networks:
      fixed_network:
        ipv4_address: 10.8.0.12

  tiles:
    build: tiles
    env_file:
    - ./.env
    command: bash /wait-for-it.sh -- tegola --config $$CONFIG serve
    volumes:
    - ./tiles/:/app
    - ./data/tiles/cache:/data/cache
    ports:
    - "9999:9999"
    depends_on:
    - postgis
    networks:
      fixed_network:
        ipv4_address: 10.8.0.13

  tiles-cleaner:
    build: tiles-cleaner
    env_file:
    - ./.env
    command: bash /entrypoint.sh
    volumes:
    - ./tiles/:/app
    - ./data/tiles:/data
    networks:
      fixed_network:
        ipv4_address: 10.8.0.14

  celery:
    build: backend
    env_file:
    - ./.env
    command: sh /wait-for-it.sh -- celery -A app.celery worker --loglevel=info
    volumes:
    - ./backend/:/code
    - ./data/tiles:/code/tiles
    depends_on:
    - postgis
    networks:
      fixed_network:
        ipv4_address: 10.8.0.15

  backend:
    build: backend
    env_file:
    - ./.env
    command: sh /wait-for-it.sh -- sh /entrypoint.sh
    ports:
    - "5000:5000"
    volumes:
    - ./backend/:/code
    - ./data/tiles:/code/tiles
    depends_on:
    - postgis
    networks:
      fixed_network:
        ipv4_address: 10.8.0.16

  frontend:
    build: frontend
    ports:
    - "4200:4200"
    volumes:
    - ./frontend/:/usr/src/app
    depends_on:
    - tiles
    - backend
    networks:
      fixed_network:
        ipv4_address: 10.8.0.17

  redis:
    image: redis:4-alpine
    command: redis-server
    volumes:
      - ./data/redis:/var/lib/redis/data
    ports:
      - '6379:6379'
    networks:
      fixed_network:
        ipv4_address: 10.8.0.18

networks:
  fixed_network:
    driver: bridge
    ipam:
     config:
       - subnet: 10.8.0.0/16
