version: "3"
services:
  postgis:
    build: postgis
    # command: ["postgres", "-c", "log_statement=all"]
    ports:
      - "5432:5432"
    volumes:
      - ./postgis/postgres-dev.conf:/var/lib/postgresql/data/postgresql.conf

  imposm:
    build: imposm

  imposm-watcher:
    build: imposm-watcher
    volumes:
      - ./imposm-watcher/:/code

  tiles:
    build: tiles
    ports:
      - "9999:9999"
    volumes:
      - ./tiles/:/app

  tiles-cleaner:
    build: tiles-cleaner
    volumes:
      - ./tiles/:/app

  celery:
    build: back
    command: celery -A batimap.app_celery:app worker --loglevel=info --queues celery --concurrency 1
    volumes:
      - ./back/:/code

  celery-slow:
    build: back
    command: celery -A batimap.app_celery:app worker --loglevel=info --queues celery_slow --concurrency 1
    volumes:
      - ./back/:/code

  back:
    build: back
    ports:
      - "5000:5000"
    volumes:
      - ./back/:/code
      - ./back/app-docker.conf/:/code/app.conf:ro

  front:
    build: front
    ports:
      - "4200:4200"
    volumes:
      - ./front/:/usr/src/app
      - ./data/front/node_modules:/usr/src/app/node_modules

  redis:
    ports:
      - "6379:6379"

  pghero:
    image: ankane/pghero
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DB
    depends_on:
      - postgis
