version: '3'
services:
  postgis:
    build: postgis
    environment:
    - POSTGRES_PASSWORD=batimap
    - POSTGRES_USER=docker
    - POSTGRES_DB=gis
    ports:
    - "5432:5432"
    volumes:
    - ./postgis/data:/var/lib/postgresql/data
    networks:
      fixed_network:
        ipv4_address: 10.5.0.10
  tiles:
    build: tiles
    command: bash /wait-for-it.sh 10.5.0.10:5432 -- tegola -config /root/config.toml
    ports:
    - "9999:9999"
    volumes:
    - ./tiles/:/root
    depends_on:
    - postgis
    networks:
      fixed_network:
        ipv4_address: 10.5.0.11
  backend:
    build: backend
    environment:
    - FLASK_APP=app.py
    command: bash /wait-for-it.sh 10.5.0.10:5432 -- flask run -h 0.0.0.0
    ports:
    - "5000:5000"
    volumes:
    - ./backend/:/code
    depends_on:
    - postgis
    networks:
      fixed_network:
        ipv4_address: 10.5.0.12
  frontend:
    build: frontend
    ports:
    - "8080:8080"
    volumes:
    - ./frontend/:/usr/src/app
    depends_on:
    - tiles
    - backend
    networks:
      fixed_network:
        ipv4_address: 10.5.0.13

networks:
  fixed_network:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
