version: '3'
services:
  postgis:
    build: postgis
    env_file:
    - ./.env
    ports:
    - "5432:5432"
    volumes:
    - ./data/postgis:/var/lib/postgresql/data

  imposm:
    build: imposm
    env_file:
    - ./.env
    entrypoint: bash /wait-for-it.sh -- /entrypoint.sh $$REGIONS
    depends_on:
    - postgis
    volumes:
    - ./data/imposm:/data

  citystats-refresher:
    build: citystats-refresher
    volumes:
    - ./citystats-refresher/:/code
    - ./data/tiles:/data/tiles
    restart: always

  tiles:
    build: tiles
    env_file:
    - ./.env
    command: bash /wait-for-it.sh -- tegola --config $$CONFIG serve
    volumes:
    - ./tiles/:/app
    - ./data/tiles/cache:/data/cache
    ports:
    - "9999:9999"
    depends_on:
    - postgis

  tiles-cleaner:
    build: tiles-cleaner
    env_file:
    - ./.env
    command: bash /entrypoint.sh
    volumes:
    - ./tiles/:/app
    - ./data/tiles:/data

  celery:
    build: back
    env_file:
    - ./.env
    command: sh /wait-for-it.sh -- celery -A app.celery worker --loglevel=info
    volumes:
    - ./back/:/code
    - ./back/app-docker.conf/:/code/app.conf:ro
    - ./data/tiles:/code/tiles
    depends_on:
    - postgis

  back:
    build: back
    env_file:
    - ./.env
    command: sh /wait-for-it.sh -- sh /entrypoint.sh
    ports:
    - "5000:5000"
    volumes:
    - ./back/:/code
    - ./back/app-docker.conf/:/code/app.conf:ro
    - ./data/tiles:/code/tiles
    depends_on:
    - postgis

  front:
    build: front
    ports:
    - "4200:4200"
    volumes:
    - ./front/:/usr/src/app
    depends_on:
    - tiles
    - back

  redis:
    image: redis:4-alpine
    command: redis-server
    volumes:
      - ./data/redis:/var/lib/redis/data
    ports:
      - '6379:6379'
