#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import gevent.monkey
gevent.monkey.patch_all()

import click
import geojson
import itertools
import logging
import requests

from flask import Flask, jsonify, request
from flask_restful import inputs
from flask_cors import CORS

from batimap import batimap
from batimap.overpassw import Overpass
from db_utils import Postgis

from bs4 import BeautifulSoup
import http.cookiejar
import urllib.request

app = Flask(__name__)
app.config.from_pyfile(app.root_path + '/app.conf')
CORS(app)

LOG = logging.getLogger(__name__)

logging.basicConfig(
    format='%(asctime)s %(message)s',
    datefmt="%H:%M:%S",
    level=logging.DEBUG if app.config[
        'DEBUG'] else logging.ERROR
)

db = Postgis(
    app.config['DB_NAME'],
    app.config['DB_USER'],
    app.config['DB_PASSWORD'],
    app.config['DB_PORT'],
    app.config['DB_HOST'],
    app.config['TILESERVER_URI'],
)

op = Overpass(app.config['OVERPASS_URI'])

all_departments = itertools.chain(
    range(1, 20), ('2A', '2B'), range(21, 96), range(971, 977))

# ROUTES


@app.route('/status/<department>', methods=['GET'])
def api_department_status(department) -> str:
    return jsonify([{x[0].insee: x[1]} for x in
                    batimap.stats(db, op, department=department, force=request.args.get('force', False))])


@app.route('/status/<department>/<city>', methods=['GET'])
def api_city_status(department, city) -> str:
    for (city, date, author) in batimap.stats(db, op, cities=[city], force=request.args.get('force', default=False, type=inputs.boolean)):
        return jsonify({city.insee: date})
    return ''


@app.route('/status/by_date/<date>')
def api_cities_for_date(date) -> str:
    return jsonify(db.get_cities_for_date(date))


@app.route('/insee/<insee>', methods=['GET'])
def api_insee(insee) -> dict:
    color_city = db.get_insee(insee)
    return geojson.dumps(color_city)


@app.route('/colors/<lonNW>/<latNW>/<lonSE>/<latSE>/<colors>', methods=['GET'])
def api_color(colors, lonNW, latNW, lonSE, latSE) -> dict:
    color_city = db.get_city_with_colors(colors.split(','), float(
        lonNW), float(latNW), float(lonSE), float(latSE))
    return geojson.dumps(color_city)


@app.route('/colors', methods=['GET'])
def api_colors_list() -> dict:
    return jsonify(db.get_colors())


@app.route('/status/<department>', methods=['GET'])
def api_status(department) -> dict:
    return jsonify(db.get_department_colors(department))


@app.route('/update/<insee>', methods=['POST'])
def api_update_insee_list(insee) -> dict:
    (_, date, _) = next(batimap.stats(db, op, cities=[insee], force=True))
    # TODO: only clear tiles if color was changed // return different status
    # codes

    # clear tiles for the zone
    db.clear_tiles(insee)
    return jsonify(date)


# CLI
@app.cli.command('initdb')
def initdb_command():
    """
    Creates required tables in PostgreSQL server.
    """
    db.create_tables()


@app.cli.command('initcadastre')
def initcadastre_command():
    """
    Imports cities cadastral status as of today.
    """
    # fixme: this won't work if app is launched in a different folder..
    code_cadastre = 'batimap/code_cadastre.csv'
    with open(code_cadastre, 'w') as fd:
        fd.write("; Generated by cadastre-conflation initcadastre CLI command.\n")

    url = 'https://www.cadastre.gouv.fr/scpc/rechercherPlan.do'

    cj = http.cookiejar.CookieJar()
    op = urllib.request.build_opener(urllib.request.HTTPCookieProcessor(cj))
    r = op.open(url)
    csrf_token = r.read().split(b'CSRF_TOKEN=')[
        1].split(b'"')[0].decode('utf-8')

    for d in all_departments:
        LOG.debug(f"Récupération des infos pour le département {d}")
        d = f'{d}'
        r2 = op.open(f"https://www.cadastre.gouv.fr/scpc/listerCommune.do?CSRF_TOKEN={csrf_token}&codeDepartement={d.zfill(3)}&libelle=&keepVolatileSession=&offset=5000")

        fr = BeautifulSoup(r2.read(), "lxml")
        for e in fr.find_all(attrs={"class": "parcelles"}):
            y = e.find(title="Ajouter au panier")
            if y is None:
                continue

            # y.get('onclick') structure: "ajoutArticle('CL098','VECT','COMU');"
            split = y.get('onclick').split("'")
            code_commune = split[1]
            format_type = split[3]

            # e.strong.string structure: "COBONNE (26400) "
            commune_cp = e.strong.string
            nom_commune = commune_cp[:-9]
            cp = commune_cp[-7:-2]

            with open(code_cadastre, 'a') as fd:
                fd.write(f"{d.zfill(2)},{d.zfill(3)},{nom_commune},{cp},{code_commune},{format_type}\n")


@app.cli.command('get-city-stats')
@click.argument('cities', nargs=-1)
@click.option('--fast', is_flag=True)
def get_city_stats(cities, fast):
    """
    Returns cadastral status of given cities.
    If status is unknown, it is computed first.
    """
    for (city, date, author) in batimap.stats(db, op, cities=cities, force=not fast):
        click.echo('{}: date={} author={}'.format(city, date, author))


@app.cli.command('get-department-stats')
@click.argument('departments', nargs=-1)
@click.option('--fast', is_flag=True)
def get_department_stats(departments, fast):
    """
    Returns cadastral status of given departments cities.
    If status is unknown, it is computed first.
    """
    for department in departments:
        for (city, date, author) in batimap.stats(db, op, department=department, force=not fast):
            click.echo('{}: date={} author={}'.format(city, date, author))


@app.cli.command('get-france-stats')
@click.option('--fast', is_flag=True)
def get_france_stats(fast):
    """
    Returns cadastral status of French cities.
    If status is unknown, it is computed first.
    """
    for department in all_departments:
        for (city, date, author) in batimap.stats(db, op, department=department, force=not fast):
            click.echo('{}: date={} author={}'.format(city, date, author))


@app.cli.command('generate-city-building')
@click.argument('cities', nargs=-1)
def generate_city_building(cities):
    """
    Download buildings for given cities. IMPROVE_ME
    """
    batimap.generate(db, cities=cities)


@app.cli.command('load-city-josm')
@click.argument('cities', nargs=-1)
@click.option('--force', is_flag=True)
def load_city_josm(cities, force):
    """
    Create and open JOSM project for given cities.
    """
    for (city, date, author) in batimap.stats(db, op, cities=cities, force=True):
        click.echo('{}: date={} author={}'.format(city, date, author))
    batimap.work(db, cities=cities, force=force)
